name: 'ko-resolve'
description: 'Use ko to do something.'
inputs:
  filename:
    description: 'Filename, directory, or URL to files to use to create the resource'
    required: true
  config:
    description: 'The docker config that ko will use to push to the repository, as json'
    required: true
  repo:
    description: 'The docker repo that will be pushed to'
    required: true

outputs:
  output:
    description: 'The output of ko'

runs:
  using: 'docker'
  image: 'Dockerfile'
